// <auto-generated />
using System;
using AnimeDbWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeDbWebApp.Data.Migrations
{
    [DbContext(typeof(AnimeDbContext))]
    [Migration("20241209192139_FullStructure")]
    partial class FullStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeDbWebApp.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier that equals mal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Short description");

                    b.Property<string>("Duration")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Duration of episode");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DATETIME2")
                        .HasComment("Last episode aired date");

                    b.Property<int?>("Episodes")
                        .HasColumnType("int")
                        .HasComment("Number of episodes");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Anime poster url");

                    b.Property<int?>("Rank")
                        .HasColumnType("int")
                        .HasComment("Anime rank");

                    b.Property<string>("Rating")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Age restriction for anime");

                    b.Property<decimal?>("Score")
                        .HasColumnType("DECIMAL(4,2)")
                        .HasComment("Populairty/liked score of anime");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasComment("Yearly anime season that anime aired");

                    b.Property<int>("SourceId")
                        .HasColumnType("int")
                        .HasComment("Source for creating the anime");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("DATETIME2")
                        .HasComment("Airing start date");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("Airing status");

                    b.Property<string>("Synopsis")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Short description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Anime title");

                    b.Property<string>("TitleEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Anime title in english translated");

                    b.Property<string>("TitleJapanese")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Anime title in japanese characters");

                    b.Property<string>("TrailerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Anime trailer url");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasComment("Type of anime(tv series, movie, etc.)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Url link to mal site");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("TypeId");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AnimeGenre", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of anime");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of genre");

                    b.HasKey("AnimeId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("AnimesGenres");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AnimeLicensor", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of anime");

                    b.Property<int>("LicensorId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of licensor(producer)");

                    b.HasKey("AnimeId", "LicensorId");

                    b.HasIndex("LicensorId");

                    b.ToTable("AnimesLicensors");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AnimeManga", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of anime");

                    b.Property<int>("MangaId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of manga");

                    b.HasKey("AnimeId", "MangaId");

                    b.HasIndex("MangaId");

                    b.ToTable("AnimesMangas");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AnimeProducer", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of anime");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of producer");

                    b.HasKey("AnimeId", "ProducerId");

                    b.HasIndex("ProducerId");

                    b.ToTable("AnimesProducers");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AnimeRelation", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of anime");

                    b.Property<int>("RelationId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of anime that have relation to animeId");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Type of relation that animes have");

                    b.HasKey("AnimeId", "RelationId");

                    b.HasIndex("RelationId");

                    b.ToTable("AnimesRelations");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AnimeStudio", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of anime");

                    b.Property<int>("StudioId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of studio(producer)");

                    b.HasKey("AnimeId", "StudioId");

                    b.HasIndex("StudioId");

                    b.ToTable("AnimesStudios");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AppUserAnime", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of anime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User unique identifier");

                    b.Property<int>("WatchingStatus")
                        .HasColumnType("int")
                        .HasComment("Watching status");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersAnimes");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AppUserManga", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of manga");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User unique identifier");

                    b.Property<int>("WatchingStatus")
                        .HasColumnType("int")
                        .HasComment("Watching status");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersMangas");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier that equals mal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Aditional information about author");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("DATETIME2")
                        .HasComment("Author birthdate");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Author family name");

                    b.Property<string>("GivenName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Author given name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Author name");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Person poster url");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Url link to mal site");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Person website");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.GenreForAnime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Genre name");

                    b.HasKey("Id");

                    b.ToTable("GenresForAnimes");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.GenreForManga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Genre name");

                    b.HasKey("Id");

                    b.ToTable("GenresForMangas");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.Magazine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier that equals mal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Magazine name");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Url link to mal site");

                    b.HasKey("Id");

                    b.ToTable("Magazines");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.Manga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier that equals mal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Short pre-story");

                    b.Property<int?>("Chapters")
                        .HasColumnType("int")
                        .HasComment("Number of chapters");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DATETIME2")
                        .HasComment("Date manga ended publishing");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Manga poster url");

                    b.Property<int?>("Rank")
                        .HasColumnType("int")
                        .HasComment("Manga rank");

                    b.Property<decimal?>("Score")
                        .HasColumnType("DECIMAL(4,2)")
                        .HasComment("Manga score");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("DATETIME2")
                        .HasComment("Date manga started publishing");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("Airing status");

                    b.Property<string>("Synopsis")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Short description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Manga title");

                    b.Property<string>("TitleEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Manga title in english translated");

                    b.Property<string>("TitleJapanese")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Manga title in japanese characters");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasComment("Type of manga(manga, light novel, etc.)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Url link to mal site");

                    b.Property<int?>("Volumes")
                        .HasColumnType("int")
                        .HasComment("Number of volumes, chapters combined in");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Mangas");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.MangaAuthor", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of author");

                    b.Property<int>("MangaId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of manga");

                    b.HasKey("AuthorId", "MangaId");

                    b.HasIndex("MangaId");

                    b.ToTable("MangasAuthors");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.MangaGenre", b =>
                {
                    b.Property<int>("MangaId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of manga");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of genre");

                    b.HasKey("MangaId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MangasGenres");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.MangaMagazine", b =>
                {
                    b.Property<int>("MangaId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of manga");

                    b.Property<int>("MagazineId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of magazine");

                    b.HasKey("MangaId", "MagazineId");

                    b.HasIndex("MagazineId");

                    b.ToTable("MangasMagazines");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.MangaRelation", b =>
                {
                    b.Property<int>("MangaId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of manga");

                    b.Property<int>("RelationId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier of manga that have relation to mangaId");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Type of relation that mangas have");

                    b.HasKey("MangaId", "RelationId");

                    b.HasIndex("RelationId");

                    b.ToTable("MangasRelations");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier that equals mal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Information about producer");

                    b.Property<DateTime?>("Established")
                        .HasColumnType("DATETIME2")
                        .HasComment("Date the producer is established");

                    b.Property<string>("ImgUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Producer image url");

                    b.Property<string>("JpName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Japanese name of the producer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("English name of the producer");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Url link to mal site of producer");

                    b.HasKey("Id");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Source name");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.TypeForAnime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Type name");

                    b.HasKey("Id");

                    b.ToTable("AnimeTypes");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.TypeForManga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Type name");

                    b.HasKey("Id");

                    b.ToTable("MangaTypes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.Anime", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.Source", "Source")
                        .WithMany("Animes")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeDbWebApp.Models.TypeForAnime", "Type")
                        .WithMany("Animes")
                        .HasForeignKey("TypeId");

                    b.Navigation("Source");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AnimeGenre", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.Anime", "Anime")
                        .WithMany("Genres")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimeDbWebApp.Models.GenreForAnime", "Genre")
                        .WithMany("Animes")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AnimeLicensor", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.Anime", "Anime")
                        .WithMany("AnimesLicensors")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimeDbWebApp.Models.Producer", "Licensor")
                        .WithMany("AnimesLicensors")
                        .HasForeignKey("LicensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Licensor");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AnimeManga", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.Anime", "Anime")
                        .WithMany("MangaAdaptations")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimeDbWebApp.Models.Manga", "Manga")
                        .WithMany("AnimeAdaptations")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AnimeProducer", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.Anime", "Anime")
                        .WithMany("AnimesProducers")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimeDbWebApp.Models.Producer", "Producer")
                        .WithMany("AnimesProducers")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AnimeRelation", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.Anime", "Anime")
                        .WithMany("AnimesRelations")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimeDbWebApp.Models.Anime", "Relation")
                        .WithMany()
                        .HasForeignKey("RelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AnimeStudio", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.Anime", "Anime")
                        .WithMany("AnimesStudios")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimeDbWebApp.Models.Producer", "Studio")
                        .WithMany("AnimesStudios")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AppUserAnime", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.Anime", "Anime")
                        .WithMany("AppUsers")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimeDbWebApp.Models.AppUser", "AppUser")
                        .WithMany("Animes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AppUserManga", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.Manga", "Manga")
                        .WithMany("AppUsers")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimeDbWebApp.Models.AppUser", "AppUser")
                        .WithMany("Mangas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.Manga", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.TypeForManga", "Type")
                        .WithMany("Mangas")
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.MangaAuthor", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.Author", "Author")
                        .WithMany("MangasAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimeDbWebApp.Models.Manga", "Manga")
                        .WithMany("MangasAuthors")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.MangaGenre", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.GenreForManga", "Genre")
                        .WithMany("Mangas")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimeDbWebApp.Models.Manga", "Manga")
                        .WithMany("Genres")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.MangaMagazine", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.Magazine", "Magazine")
                        .WithMany("MangasMagazines")
                        .HasForeignKey("MagazineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimeDbWebApp.Models.Manga", "Manga")
                        .WithMany("MangasMagazines")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Magazine");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.MangaRelation", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.Manga", "Manga")
                        .WithMany("MangaRelations")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimeDbWebApp.Models.Manga", "Relation")
                        .WithMany()
                        .HasForeignKey("RelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeDbWebApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AnimeDbWebApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.Anime", b =>
                {
                    b.Navigation("AnimesLicensors");

                    b.Navigation("AnimesProducers");

                    b.Navigation("AnimesRelations");

                    b.Navigation("AnimesStudios");

                    b.Navigation("AppUsers");

                    b.Navigation("Genres");

                    b.Navigation("MangaAdaptations");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.AppUser", b =>
                {
                    b.Navigation("Animes");

                    b.Navigation("Mangas");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.Author", b =>
                {
                    b.Navigation("MangasAuthors");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.GenreForAnime", b =>
                {
                    b.Navigation("Animes");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.GenreForManga", b =>
                {
                    b.Navigation("Mangas");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.Magazine", b =>
                {
                    b.Navigation("MangasMagazines");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.Manga", b =>
                {
                    b.Navigation("AnimeAdaptations");

                    b.Navigation("AppUsers");

                    b.Navigation("Genres");

                    b.Navigation("MangaRelations");

                    b.Navigation("MangasAuthors");

                    b.Navigation("MangasMagazines");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.Producer", b =>
                {
                    b.Navigation("AnimesLicensors");

                    b.Navigation("AnimesProducers");

                    b.Navigation("AnimesStudios");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.Source", b =>
                {
                    b.Navigation("Animes");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.TypeForAnime", b =>
                {
                    b.Navigation("Animes");
                });

            modelBuilder.Entity("AnimeDbWebApp.Models.TypeForManga", b =>
                {
                    b.Navigation("Mangas");
                });
#pragma warning restore 612, 618
        }
    }
}
